-- Imagen principal optimizada por producto.
-- Migracion aditiva: el codigo anterior ignora la columna y sigue funcionando.

ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS imagen_path text;

COMMENT ON COLUMN public.productos.imagen_path IS
  'Ruta base versionada en Storage: {producto_id}/{uuid}. Las variantes son thumb.webp y detail.webp.';

CREATE TABLE IF NOT EXISTS public.producto_imagenes_huerfanas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id bigint REFERENCES public.productos(id) ON DELETE SET NULL,
  path text NOT NULL UNIQUE,
  motivo text NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  limpiado_en timestamptz
);

ALTER TABLE public.producto_imagenes_huerfanas ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.producto_imagenes_huerfanas IS
  'Registro operativo de versiones de imagen cuya eliminacion de Storage debe reintentarse.';

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'productos',
  'productos',
  true,
  307200,
  ARRAY['image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- No se crean policies INSERT/UPDATE/DELETE para anon. Las escrituras se hacen
-- exclusivamente desde el servidor con service_role. El bucket publico permite
-- servir las imagenes sin autenticar, pero no concede permisos de escritura.
